#!/usr/bin/env python3

import re
import sys

def invert(colour):
    inv = 0xFFFFFF ^ int(colour[1:], 16)
    return f"#{inv:06X}"

def replace(input):
    return re.sub(r"#\w{6}\b", lambda m: invert(m.group()), input)

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("please provide <input> <output>", file=sys.stderr)
        sys.exit(1)

    file_in, file_out = sys.argv[1:]
    with open(file_in, "r") as file_in:
        with open(file_out, "w") as file_out:
            file_out.write(replace(file_in.read()))
