#!/usr/bin/env bash

set -eu

usage() {
    echo "usage:" >&2
    echo "  $0 install <repo>" >&2
    echo "  $0 uninstall <name>" >&2
    exit 1
}

case "${1-}" in
"install")
    repo="${2-}"
    [[ -n "$repo" ]] || usage

    name="${repo##*/}"
    name="${name%.git}"
    path="common/.config/fish/plugins/$name"

    git submodule add -f "$repo" "$path"
    ;;

"uninstall")
    name="${2-}"
    [[ -n "$name" ]] || usage

    path="common/.config/fish/plugins/$name"

    git submodule deinit -f "$path"
    git rm -f "$path"
    ;;

*)
    usage
    ;;
esac
