#!/usr/bin/env bash

# intended to be run from termux
# $ termux-setup-storage
# $ curl -sSL "https://raw.githubusercontent.com/sentriz/dotfiles/master/install-phone-all" | bash -s - storage/path/to/key

set -e

function once() {
    flag="$HOME/.cache/dot_once_$1"
    test -f "$flag" && return
    "$1" "${@:2}" \
        && touch "$flag" \
        || exit 1
}

function setup-pacs() {
    apt update
    apt upgrade
    apt install --yes -o DPkg::Options::="--force-confnew" \
        fish \
        git \
        gnupg \
        neovim \
        openssh \
        python \
        stow \
        wget
}

function setup-priv-key() {
    if [[ ! -f "$1" ]]; then
        echo "please provide a private key" >&2
        return 1
    fi
    priv_key="$1"
    GPG_TTY="$(tty)" gpg --import "$priv_key"
    rm "$priv_key"
}

function setup-dots() {
    dots_dir="$HOME/projects/dotfiles"
    mkdir -p "$dots_dir" >/dev/null 2>&1
    git clone --recurse-submodules "https://github.com/sentriz/dotfiles.git" "$dots_dir"
    cd "$dots_dir"
    ./install-common
    ./install-phone
    cd
}

once setup-pacs
once setup-priv-key "$1"
once setup-dots

chsh fish
exec fish
