#!/usr/bin/env bash

# intended to be run from termux
# curl -sSL "https://raw.githubusercontent.com/sentriz/dotfiles/master/install_phone_all" | sh -s - path/to/key

set -e

if test "$#" -ne 1; then
    echo "please provide a private key" >&2
    exit 1
fi

conf_dots_dir="$HOME/projects/dotfiles"
conf_priv_key="$1"

mkdir -p "$HOME/.config/fish/functions/" >/dev/null 2>&1
mkdir -p "$HOME/projects/dotfiles/" >/dev/null 2>&1

function once() {
    flag="$HOME/.cache/dot_once_$1"
    test ! -f "$flag" && "$1" && touch "$1"
}

function setup-pacs() {
    apt update
    apt upgrade
    apt install \
        fish \
        git \
        gnupg \
        neovim \
        openssh \
        python \
        stow \
        wget
}

function setup-priv-key() {
    gpg --import "$conf_priv_key"
    rm "$conf_priv_key"
}

function setup-shell() {
    wget 'https://git.io/fundle' -O "$HOME/.config/fish/functions/fundle.fish"
    fish -ic "fundle install"
    chsh -s fish
}

function setup-dots() {
    git clone --recurse-submodules "https://github.com/sentriz/dotfiles.git" "$conf_dots_dir"
    cd "$conf_dots_dir"
    ./install-common
    ./install-phone
    cd
}

once setup-pacs
once setup-priv-key
once setup-shell
once setup-dots

exec fish
