#!/usr/bin/env bash

set -e

stow -v --no-folding --ignore ".*\/tests\/.*" --target ~ -R conf_common

chown -R "$(whoami)" ~/.gnupg/
find ~/.gnupg -type f -exec chmod 600 {} \;
find ~/.gnupg -type d -exec chmod 700 {} \;
