#!/usr/bin/env bash

set -e

if test $# -ne 1; then
    echo "please provide a <repo>" >&2
    exit 1
fi

name="$1"
paths=(conf_common/.local/share/nvim/site/pack/*/opt/"$1")
path="${paths[0]}"

if test ! -d "$path"; then
    echo "plugin $name not found" >&2
    exit 1
fi

git submodule deinit -f "$path"
git rm -f "$path"

echo "##############"
echo "remove config:"
echo "packadd! $name"
