#!/usr/bin/env bash

set -e

if test $# -ne 1; then
    echo "please provide a name" >&2
    exit 1
fi

name="$1"
path="conf_common/.local/share/nvim/site/pack/plugins/start/$name"

git submodule deinit -f "$path"
git rm -f "$path"
