#!/usr/bin/env bash

set -eu

usage() {
    echo "usage:" >&2
    echo "  $0 install <repo> [branch]" >&2
    echo "  $0 uninstall <name>" >&2
    exit 1
}

case "${1-}" in
"install")
    repo="${2-}"
    branch="${3-}"
    [[ -n "$repo" ]] || usage

    name="${repo##*/}"
    name="${name%.git}"
    path="common/.local/share/nvim/site/pack/plugins/start/$name"

    extra_args=()
    [[ -n "$branch" ]] && extra_args=(-b "$branch")

    git submodule add "${extra_args[@]}" -f "$repo" "$path"
    ;;

"uninstall")
    name="${2-}"
    [[ -n "$name" ]] || usage

    path="common/.local/share/nvim/site/pack/plugins/start/$name"

    git submodule deinit -f "$path"
    git rm -f "$path"
    ;;

*)
    usage
    ;;
esac
