shell=/usr/bin/fish
# theme: font /^font=(.*):size=/
font=Source Code Pro:size=13
dpi-aware=no

[scrollback]
lines=20000

[bell]
notify=yes

[colors-dark]
foreground=E5E5E5 # theme: grey2
background=333333 # theme: background
cursor=333333 E5E5E5 # theme: background grey2
regular0=404040 # theme: grey7
regular1=FF6568 # theme: red
regular2=05DF72 # theme: green
regular3=F7C902 # theme: yellow
regular4=57A2FF # theme: blue
regular5=EC6DFF # theme: magenta
regular6=02D1EC # theme: cyan
regular7=D4D4D4 # theme: grey3
bright0=A1A1A1 # theme: grey4
bright1=FFA3A4 # theme: brred
bright2=7BF1A8 # theme: brgreen
bright3=FFE031 # theme: bryellow
bright4=91C5FF # theme: brblue
bright5=F2A9FF # theme: brmagenta
bright6=53EAFD # theme: brcyan
bright7=F5F5F5 # theme: grey1

[colors-light]
foreground=333333 # theme: background
background=F5F5F5 # theme: grey1
cursor=F5F5F5 333333 # theme: grey1 background
regular0=404040 # theme: grey7
regular1=E30117 # theme: light-red
regular2=02A447 # theme: light-green
regular3=CA8A01 # theme: light-yellow
regular4=155DFC # theme: light-blue
regular5=C501DA # theme: light-magenta
regular6=0291B2 # theme: light-cyan
regular7=737373 # theme: grey5
bright0=525252 # theme: grey6
bright1=FB2C36 # theme: light-brred
bright2=01C65A # theme: light-brgreen
bright3=EAB302 # theme: light-bryellow
bright4=3280FF # theme: light-brblue
bright5=E12AFB # theme: light-brmagenta
bright6=04B6D4 # theme: light-brcyan
bright7=A1A1A1 # theme: grey4

[key-bindings]
unicode-input=none
show-urls-launch=Control+Shift+j
show-urls-copy=Control+Shift+u
show-urls-persistent=none
pipe-command-output=[wl-copy -n] Control+Shift+l

[desktop-notifications]
command=foot-notify ${action-argument} -- ${title} ${body}
command-action-argument=--action ${action-name}=${action-label}
