exec 'source' . expand("~/.config/nvim/conf_plugins.vim")
exec 'source' . expand("~/.config/nvim/conf_appearance.vim")
exec 'source' . expand("~/.config/nvim/conf_auto_commands.vim")
exec 'source' . expand("~/.config/nvim/conf_improvements.vim")
exec 'source' . expand("~/.config/nvim/conf_mappings.vim")
exec 'source' . expand("~/.config/nvim/conf_lang_server.vim")
