volume-max=600
no-audio-display
gpu-context=wayland
ytdl-format=bestvideo[height<=?1080][fps<=?30][vcodec!=?vp9]+bestaudio/best

screenshot-format=png
screenshot-template="%F-%p"
deband=no

# theme: font /=(.*)/
osd-font=Source Code Pro
# theme: grey2
osd-color=#E5E5E5
# theme: background
osd-border-color=#333333
screenshot-high-bit-depth=no
