#!/usr/bin/env bash

# this is working for me with one sink and
# - pulseaudio
# - pulseaudio-alsa
# - alsa-utils

resp="$(amixer sget "$BLOCK_INSTANCE")"
grep -q '\[off\]' <<< "$resp" && echo 'muted' && exit
grep -Po 'Left.*\[\K([0-9]+%)(?=\])' <<< "$resp"
