#!/usr/bin/env bash

# setup
cache_dir="${XDG_CACHE_HOME:-"$HOME/.cache/boi_balance"}"
mkdir -p "$cache_dir"
balance_file="$cache_dir/balance"
lock_file="$cache_dir/lock"

if test -e "$lock_file"; then
    >&2 echo "already running"
    exit 1
else
    touch "$lock_file"
fi

# start
filter=".Summary.Accounts
        | .[]
        | select(.Name == \"$1\") 
        | .Balance"
balance=$(boi_balance | jq -r "$filter")

# notify change in balance
last_balance=$(cat "$balance_file.old")
delta=$(echo "$balance" - "$last_balance" | bc)
if ! test "$delta" -eq "0"; then
    [[ "$delta" == -* ]] || delta="+$delta"
    notify-send -- "boi balance" "$delta"
fi

# write balance to file, and tell i3blocks to call main script,
# which will see and cat the new balance
echo "$balance" > "$balance_file"
pkill -RTMIN+5 i3blocks

# remove lock
rm "$lock_file"
