#!/usr/bin/bash

function format() {
    printf "%'.2f\n" "$1" | sed -E 's/(\-|\+)?(.*)/\1€\2/' 
}

function get-balance-boi() {
    boi_balance $(pass money/boi/365/username) \
                $(pass money/boi/365/phone_number) \
                $(pass money/boi/365/password) \
                $(pass money/boi/365/date_of_birth)
}

function get-balance-revolut() {
    revolut_cli.py --language en \
                   --token $(pass money/revolut/token) \
        | sed '2q;d' \
        | awk -F ',' '{print $2}'
}

function get-balance() {
    case "$BLOCK_INSTANCE" in
        'boi')     get-balance-boi;;
        'revolut') get-balance-revolut;;
        *)         echo '0.00';;
    esac
}

balance="$(get-balance 2> /dev/null)" 
[ -n "$balance" ] && format "$balance"
