#!/usr/bin/bash

current_day=$(date +%d)
last_working_day=$(cal -m \
    | sed -E 's/.{6}$//' \
    | grep -E '\w+' \
    | tail -n 1 \
    | awk '{print $NF}')
left=$(expr $last_working_day - $current_day)

printf "%d days\n" $left
