#!/usr/bin/env bash

# this is working for me with one sink and
# - pulseaudio
# - pulseaudio-alsa
# - pulseaudio-bluetooth
# - alsa-utils
# installed

if amixer sget Master | grep -q '\[off\]'; then
    echo 'muted'
    exit
fi

amixer sget Master | grep -Po 'Left.*\[\K([0-9]+%)(?=\])'
