#!/usr/bin/env bash

message=$(head -n 1 $1)

if ! grep --extended-regexp --silent '^([0-9a-z_,]+\:|Merge|fixup\!)\s.*$' <<< $message; then
    echo 'commit message must be in the format `<software>: <message>`' >&2
    echo "rejecting message \`$message\`" >&2
    exit 1
fi
