#!/usr/bin/env bash

if [[ $# -ne 3 ]]; then
    echo "please provide <server> <download_dir> <link>" >&2
    exit 1
fi

server="$1"
download_dir="$2"
link="$3"
notify_file="$(mktemp)"
username="$(secret transmission_"${server}"_username)"
password="$(secret transmission_"${server}"_password)"
url="$(secret transmission_"${server}"_rpc_url)"

notify() {
    notify-send.sh --replace-file "$notify_file" "$@"
}

request() {
    curl --silent --anyauth --user "$username:$password" "$url" "$@"
}

get_key() {
    grep -Po "X-Transmission-Session-Id\: \w+"
}

notify "adding torrent" "$link"

read -r -d '' request_data <<EOF
{ 
  "method": "torrent-add",
  "arguments": {
    "filename": "$link",
    "download-dir": "$download_dir"
  }
} 
EOF

request \
    --header "$(request | get_key)" \
    --data-binary "$request_data"

notify "adding torrent" "done"
