status_path {
	shell echo "$XDG_STATE_HOME/pimsync"
}

storage calendars_local {
	type vdir/icalendar
	path {
		shell echo "$CALENDARS_DIR"
	}
}

storage calendars_radicale {
	type caldav
	url {
		cmd secret radicale_url
	}
	discovery context
	username {
		cmd secret radicale_username
	}
	password {
		cmd secret radicale_password
	}
}

storage calendars_work {
	type webcal
	url {
		cmd secret google_work_ical_url
	}
	collection_id work
}

storage contacts_local {
	type vdir/vcard
	path {
		shell echo "$CONTACTS_DIR"
	}
}

storage contacts_radicale {
	type carddav
	url {
		cmd secret radicale_url
	}
	discovery context
	username {
		cmd secret radicale_username
	}
	password {
		cmd secret radicale_password
	}
}

pair calendars {
	storage_a calendars_local
	storage_b calendars_radicale
	collections from b
	conflict_resolution keep b
}

pair calendars_work {
	storage_a calendars_work
	storage_b calendars_local
	collection work
	one_way
}

pair contacts {
	storage_a contacts_radicale
	storage_b contacts_local
	collections from a
	one_way
}
